version : '2'
services:
    tor-relay:
      image: amgxv/dockerized-tor-relay:armv7
      container_name: NAME
      volumes:
        - tor_data:/var/lib/tor
        - tor_logs:/var/log/tor/
        - ./torrc:/etc/tor/torrc
      ports:
        - 9001:9001
        - 9030:9030
      restart: always

volumes:
  tor_data:
  tor_logs:
